server:
  port: 8097
spring:
  datasource:
    url: jdbc:postgresql://167.172.158.67:5432/mood_tracker_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Flyway settings
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: cam1hy2d32sxm2t3a
  expiration: 86400000
